// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbsk9OT5ILrgD73GPQsBQdByM9AqDqQTc',
    appId: '1:687763640830:web:df21713396f61bc868b0af',
    messagingSenderId: '687763640830',
    projectId: 'chatapp-b9cb7',
    authDomain: 'chatapp-b9cb7.firebaseapp.com',
    storageBucket: 'chatapp-b9cb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIF26ZhVqKGJu8cIeE1FWzofDKOM3dPOg',
    appId: '1:687763640830:android:57ffd326510bd1e468b0af',
    messagingSenderId: '687763640830',
    projectId: 'chatapp-b9cb7',
    storageBucket: 'chatapp-b9cb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb1Zrbdo1obf-6IyBsr7wmzZYQTe-hvyU',
    appId: '1:687763640830:ios:1a76327ac6971b3268b0af',
    messagingSenderId: '687763640830',
    projectId: 'chatapp-b9cb7',
    storageBucket: 'chatapp-b9cb7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
